---
# tasks file for vector-role
- name: 'Get vector rpm'
 ansible.builtin.get_url:
 url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
 dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
 mode: 0644
- name: Install vector rpm
 become: true
 ignore_errors: true
 ansible.builtin.yum:
 name:
 - vector-{{ vector_version }}-1.x86_64.rpm